#
# Build configuration file to run build on azure-pipelines
#
name: $(Build.Major).$(Build.Minor).$(date:yyMM).$(DayOfMonth)$(rev:rr)
trigger: none
resources:
- repo: self
variables:
  Build.Major: 0
  Build.Minor: 0
  LibrariesNCRootFolder: $(System.DefaultWorkingDirectory)
  Assembly.Version: $(Build.BuildNumber)
  Nuget.Version: $(Assembly.Version)-preview

steps:
- template: Build/step-build-libs.yml
- template: Build/step-wrap-up.yml

